FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["CarrierApi/CarrierApi.csproj", "CarrierApi/"]
RUN dotnet restore "CarrierApi/CarrierApi.csproj"
COPY . .
WORKDIR "/src/CarrierApi"
RUN dotnet publish "CarrierApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "CarrierApi.dll"]
